export const SET_FAVORITE_FILTER = 'SET_FAVORITE_FILTER'
export const ADD_AS_FAVORITE = 'ADD_AS_FAVORITE'
export const REMOVE_AS_FAVORITE = 'REMOVE_AS_FAVORITE'
export const CLEAR_FAVORITED = 'CLEAR_FAVORITED'